<a href="https://colab.research.google.com/github/saloniganvir2004-sketch/ML_Practicals/blob/main/ML_Practicals/N_K_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("NxK_Matrix.csv")
print("Original Matrix:\n", df)
print("\nMatrix Shape:", df.shape)

Original Matrix:
    Col1  Col2  Col3  Col4
0    11    11     5     5
1    10     5    10    11
2     8     4     7     6
3    14     1     2    18
4    12     2     9     8

Matrix Shape: (5, 4)


In [ ]:
transpose = df.T
print("\nTranspose of Matrix:\n", transpose)


Transpose of Matrix:
        0   1  2   3   4
Col1  11  10  8  14  12
Col2  11   5  4   1   2
Col3   5  10  7   2   9
Col4   5  11  6  18   8


In [ ]:
col_sum = df.sum()
print("\nSum of Each Column:\n", col_sum)


Sum of Each Column:
 Col1    55
Col2    23
Col3    33
Col4    48
dtype: int64


In [ ]:
row_mean = df.mean(axis=1)
print("\nMean of Each Row:\n", row_mean)


Mean of Each Row:
 0    8.00
1    9.00
2    6.25
3    8.75
4    7.75
dtype: float64


In [ ]:
added_matrix = df + df
print("\nMatrix Addition (A + A):\n", added_matrix)


Matrix Addition (A + A):
    Col1  Col2  Col3  Col4
0    22    22    10    10
1    20    10    20    22
2    16     8    14    12
3    28     2     4    36
4    24     4    18    16


In [ ]:
A = df.to_numpy()
multiplied = np.dot(A, A.T)
print("\nMatrix Multiplication (A × Aᵗ):\n", multiplied)


Matrix Multiplication (A × Aᵗ):
 [[292 270 197 265 239]
 [270 346 236 363 308]
 [197 236 165 238 215]
 [265 363 238 525 332]
 [239 308 215 332 293]]
